trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Templates'
    backendServiceArm: 'Suscripción de Azure 1(23cb500a-b7c2-41ee-821a-d3f3a40d97bd)'
    backendAzureRmResourceGroupName: 'dev1'
    backendAzureRmStorageAccountName: 'storageiesgn'
    backendAzureRmContainerName: 'contenedoriesgn1'
    backendAzureRmKey: 'terraform.tfstate'
  displayName: 'Terraform Init'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Templates'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: 'Suscripción de Azure 1(23cb500a-b7c2-41ee-821a-d3f3a40d97bd)'
  displayName: 'Terraform Destroy'